@testable import FoundationLocalization
import XCTest

final class FoundationLocalizationTests: XCTestCase {
    func testTranslations() {
        XCTAssertEqual("plans".localized(.netherlands), "Plannen")
        XCTAssertEqual("settings".localized(.netherlands), "Instellingen")
        XCTAssertEqual("appearance".localized(.netherlands), "Weergave")
        XCTAssertEqual("light".localized(.netherlands), "Licht")
        XCTAssertEqual("dark".localized(.netherlands), "Donker")
        XCTAssertEqual("language".localized(.netherlands), "Taal")
        XCTAssertEqual("weight".localized(.netherlands), "Gewicht")
        XCTAssertEqual("data".localized(.netherlands), "Gegevens")
        XCTAssertEqual("resetLabel".localized(.netherlands), "Reset calorieën en afstanden")
        XCTAssertEqual("resetQuestion".localized(.netherlands), "Weet je zeker dat je calorieën en afstanden wilt resetten?")
        XCTAssertEqual("reset".localized(.netherlands), "Resetten")
        XCTAssertEqual("cancel".localized(.netherlands), "Annuleren")
        XCTAssertEqual("start".localized(.netherlands), "Starten")
        XCTAssertEqual("pause".localized(.netherlands), "Pauze")
        XCTAssertEqual("resume".localized(.netherlands), "Doorgaan")
        XCTAssertEqual("save".localized(.netherlands), "Opslaan")
        XCTAssertEqual("loadHealth".localized(.netherlands), "Laden vanaf Health")
        XCTAssertEqual("information".localized(.netherlands), "Informatie")
        XCTAssertEqual("version".localized(.netherlands), "Versie:")

        XCTAssertEqual("plans".localized(.english), "Plans")
        XCTAssertEqual("settings".localized(.english), "Settings")
        XCTAssertEqual("appearance".localized(.english), "Appearance")
        XCTAssertEqual("light".localized(.english), "Light")
        XCTAssertEqual("dark".localized(.english), "Dark")
        XCTAssertEqual("language".localized(.english), "Language")
        XCTAssertEqual("weight".localized(.english), "Weight")
        XCTAssertEqual("data".localized(.english), "Data")
        XCTAssertEqual("resetLabel".localized(.english), "Reset calories and distances")
        XCTAssertEqual("resetQuestion".localized(.english), "Are you sure you want to reset calories and distances?")
        XCTAssertEqual("reset".localized(.english), "Reset")
        XCTAssertEqual("cancel".localized(.english), "Cancel")
        XCTAssertEqual("start".localized(.english), "Start")
        XCTAssertEqual("pause".localized(.english), "Pause")
        XCTAssertEqual("resume".localized(.english), "Resume")
        XCTAssertEqual("save".localized(.english), "Save")
        XCTAssertEqual("loadHealth".localized(.english), "Load from Health")
        XCTAssertEqual("information".localized(.english), "Information")
        XCTAssertEqual("version".localized(.english), "Version:")
    }
}
