@testable import FoundationLocalization
import XCTest

final class FoundationLocalizationTests: XCTestCase {
    func testTranslations() {
        XCTAssertEqual("plans".localized(.netherlands), "Plannen")
        XCTAssertEqual("settings".localized(.netherlands), "Instellingen")
        XCTAssertEqual("appearance".localized(.netherlands), "Weergave")
        XCTAssertEqual("light".localized(.netherlands), "Licht")
        XCTAssertEqual("dark".localized(.netherlands), "Donker")
        XCTAssertEqual("language".localized(.netherlands), "Taal")
        XCTAssertEqual("weight".localized(.netherlands), "Gewicht")
        XCTAssertEqual("data".localized(.netherlands), "Gegevens")
        XCTAssertEqual("resetLabel".localized(.netherlands), "Reset calorieën en afstanden")
        XCTAssertEqual("resetQuestion".localized(.netherlands), "Weet je zeker dat je calorieën en afstanden wilt resetten?")
        XCTAssertEqual("reset".localized(.netherlands), "Resetten")
        XCTAssertEqual("cancel".localized(.netherlands), "Annuleren")
        XCTAssertEqual("start".localized(.netherlands), "Starten")
        XCTAssertEqual("pause".localized(.netherlands), "Pauze")
        XCTAssertEqual("resume".localized(.netherlands), "Doorgaan")
        XCTAssertEqual("save".localized(.netherlands), "Opslaan")
        XCTAssertEqual("loadHealth".localized(.netherlands), "Laden vanaf Health")
        XCTAssertEqual("information".localized(.netherlands), "Informatie")
        XCTAssertEqual("version".localized(.netherlands), "Versie:")

        XCTAssertEqual("plans".localized(.english), "Plans")
        XCTAssertEqual("settings".localized(.english), "Settings")
        XCTAssertEqual("appearance".localized(.english), "Appearance")
        XCTAssertEqual("light".localized(.english), "Light")
        XCTAssertEqual("dark".localized(.english), "Dark")
        XCTAssertEqual("language".localized(.english), "Language")
        XCTAssertEqual("weight".localized(.english), "Weight")
        XCTAssertEqual("data".localized(.english), "Data")
        XCTAssertEqual("resetLabel".localized(.english), "Reset calories and distances")
        XCTAssertEqual("resetQuestion".localized(.english), "Are you sure you want to reset calories and distances?")
        XCTAssertEqual("reset".localized(.english), "Reset")
        XCTAssertEqual("cancel".localized(.english), "Cancel")
        XCTAssertEqual("start".localized(.english), "Start")
        XCTAssertEqual("pause".localized(.english), "Pause")
        XCTAssertEqual("resume".localized(.english), "Resume")
        XCTAssertEqual("save".localized(.english), "Save")
        XCTAssertEqual("loadHealth".localized(.english), "Load from Health")
        XCTAssertEqual("information".localized(.english), "Information")
        XCTAssertEqual("version".localized(.english), "Version:")
    }

    func testLocalizationViewModel() {
        let localizationManager = LocalizationViewModel()

        // Default language
        XCTAssertEqual(localizationManager.language, .english)

        localizationManager.save(LanguageCode.netherlands)
        XCTAssertEqual(localizationManager.language, LanguageCode.netherlands)

        localizationManager.load()
        XCTAssertEqual(localizationManager.language, LanguageCode.netherlands)

        XCTAssertEqual("plans".localized(localizationManager.language), "Plannen")
        XCTAssertEqual("settings".localized(localizationManager.language), "Instellingen")
        XCTAssertEqual("appearance".localized(localizationManager.language), "Weergave")
        XCTAssertEqual("light".localized(localizationManager.language), "Licht")
        XCTAssertEqual("dark".localized(localizationManager.language), "Donker")
        XCTAssertEqual("language".localized(localizationManager.language), "Taal")
        XCTAssertEqual("weight".localized(localizationManager.language), "Gewicht")
        XCTAssertEqual("data".localized(localizationManager.language), "Gegevens")
        XCTAssertEqual("resetLabel".localized(localizationManager.language), "Reset calorieën en afstanden")
        XCTAssertEqual("resetQuestion".localized(localizationManager.language), "Weet je zeker dat je calorieën en afstanden wilt resetten?")
        XCTAssertEqual("reset".localized(localizationManager.language), "Resetten")
        XCTAssertEqual("cancel".localized(localizationManager.language), "Annuleren")
        XCTAssertEqual("start".localized(localizationManager.language), "Starten")
        XCTAssertEqual("pause".localized(localizationManager.language), "Pauze")
        XCTAssertEqual("resume".localized(localizationManager.language), "Doorgaan")
        XCTAssertEqual("save".localized(localizationManager.language), "Opslaan")
        XCTAssertEqual("loadHealth".localized(localizationManager.language), "Laden vanaf Health")
        XCTAssertEqual("information".localized(localizationManager.language), "Informatie")
        XCTAssertEqual("version".localized(localizationManager.language), "Versie:")

        localizationManager.save(LanguageCode.english)
        XCTAssertEqual(localizationManager.language, LanguageCode.english)

        localizationManager.load()
        XCTAssertEqual(localizationManager.language, LanguageCode.english)

        XCTAssertEqual("plans".localized(localizationManager.language), "Plans")
        XCTAssertEqual("settings".localized(localizationManager.language), "Settings")
        XCTAssertEqual("appearance".localized(localizationManager.language), "Appearance")
        XCTAssertEqual("light".localized(localizationManager.language), "Light")
        XCTAssertEqual("dark".localized(localizationManager.language), "Dark")
        XCTAssertEqual("language".localized(localizationManager.language), "Language")
        XCTAssertEqual("weight".localized(localizationManager.language), "Weight")
        XCTAssertEqual("data".localized(localizationManager.language), "Data")
        XCTAssertEqual("resetLabel".localized(localizationManager.language), "Reset calories and distances")
        XCTAssertEqual("resetQuestion".localized(localizationManager.language), "Are you sure you want to reset calories and distances?")
        XCTAssertEqual("reset".localized(localizationManager.language), "Reset")
        XCTAssertEqual("cancel".localized(localizationManager.language), "Cancel")
        XCTAssertEqual("start".localized(localizationManager.language), "Start")
        XCTAssertEqual("pause".localized(localizationManager.language), "Pause")
        XCTAssertEqual("resume".localized(localizationManager.language), "Resume")
        XCTAssertEqual("save".localized(localizationManager.language), "Save")
        XCTAssertEqual("loadHealth".localized(localizationManager.language), "Load from Health")
        XCTAssertEqual("information".localized(localizationManager.language), "Information")
        XCTAssertEqual("version".localized(localizationManager.language), "Version:")
    }
}
